const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 199,
    img: './images/item-1.jpeg',
    desc: `ingrident's to be written here `,
},
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 139,
    img: './images/item-2.jpeg',
    desc: `ingrident's to be written here `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 99,
    img: './images/item-3.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 209,
    img: './images/item-4.jpeg',
    desc: `ingrident's to be written here `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 229,
    img: './images/item-5.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 189,
    img: './images/item-6.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 99,
    img: './images/item-7.jpeg',
    desc: `ingrident's to be written here `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 129,
    img: './images/item-8.jpeg',
    desc: `ingrident's to be written here  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 169,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 10,
    title: 'quarantine buddy',
    category: 'Dinner',
    price: 160,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 11,
    title: 'quarantine buddy',
    category: 'Desert',
    price: 129,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 12,
    title: 'quarantine buddy',
    category: 'Pizza',
    price: 150,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 13,
    title: 'quarantine buddy',
    category: 'Burger',
    price: 145,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 14,
    title: 'quarantine buddy',
    category: 'Drinks',
    price: 195,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  {
    id: 15,
    title: 'quarantine buddy',
    category: 'Hot Beverage',
    price: 240,
    img: './images/item-9.jpeg',
    desc: `ingrident's to be written here`,
  },
  
];
export default menu;
